### ISSUE TITLE
[VM/GameStation] Automatic Configuration

### ISSUE THREAD

**Issue by mirceanton** [mirceanton/amir-hlb#31]
```yaml
OS: Win10

Programs:
- Steam

Utility Programs:
- 7zip
- VLC
- VsCode
```

**Comment by mirceanton** [comment]
```yaml
hosts: windows
tasks:

    name: Download steam
    win_get_url:
    url: https://steamcdn-a.akamaihd.net/client/installer/SteamSetup.exe
    dest: C:\SteamSetup.exe
    register: result

    name: Check for download errors
    fail:
    msg: "Failed to download Steam. Error: {{ result.msg }}"
    when: result.failed

    name: Install steam
    win_shell: C:\SteamSetup.exe
    register: result

    name: Check for installation errors
    fail:
    msg: "Failed to install Steam. Error: {{ result.msg }}"
    when: result.failed

    name: Add steam credentials
    win_shell: |
    steaCMD.exe +login {{ username }} {{ password }}
    exit 0
    register: result

    name: Check for login errors
    fail:
    msg: "Failed to login to Steam. Error: {{ result.msg }}"
    when: result.failed
```
