### ISSUE TITLE
[VM/AudioStation] Automatic Configuration

### ISSUE THREAD

**Issue by mirceanton** [mirceanton/amir-hlb#32]
```yaml
OS: Win10

Programs:
  - Reaper
  - Kontakt Player

Utility Programs:
  - CRU
  - VBCable
  - 7zip
  - VLC
  - VSCode
```
