### ISSUE TITLE
[VM/VideoStation]

### ISSUE THREAD

**Issue by mirceanton** [mirceanton/amir-hlb#33]
```yaml
OS: Win10

Programs:
  - DaVinci Resolve

Utility Programs:
  - CRU
  - VBCable
  - 7zip
  - VLC
  - VSCode
```
