### ISSUE TITLE
[VM/Electronics] Automatic Configuration

### ISSUE THREAD

**Issue by mirceanton** [mirceanton/amir-hlb#34]
```yaml
OS: Win10

Programs:
  - KiCad
  - FreeCAD
  - Arduino IDE
  - VSCode

Utility Programs:
  - CRU
  - VBCable
  - 7zip
  - VLC
```
